In [ ]:
import numpy as np 

np.random.seed(42)

In [23]:
a = np.random.randint(0, 10, size=(2, 3))
b = np.random.randint(0, 10, size=(4, 3))

In [95]:
a

array([[9, 3, 1],
       [5, 5, 5]])

In [96]:
b

array([[0, 4, 7],
       [0, 3, 2],
       [5, 4, 0],
       [5, 7, 3]])

In [70]:
dists = np.zeros((a.shape[0], b.shape[0]))
for i in range(a.shape[0]):
    for j in range(b.shape[0]):
        dists[i, j] = np.sqrt( np.sum( (a[i]- b[j]) ** 2 ) )
dists

array([[10.86278049,  9.05538514,  4.24264069,  6.        ],
       [ 5.47722558,  6.164414  ,  5.09901951,  2.82842712]])

In [110]:
dists = np.zeros((a.shape[0], b.shape[0]))
for i in range(a.shape[0]):
    dists[i, :] = np.sqrt(np.sum((a[i] - b)**2, axis=1))
dists

array([[10.86278049,  9.05538514,  4.24264069,  6.        ],
       [ 5.47722558,  6.164414  ,  5.09901951,  2.82842712]])

In [119]:
a = [1,2,3,2,1,2,2,2,110]
values, counts = np.unique(a, return_counts=True)
ind = np.argmax(counts)
print(values[ind])

2


In [77]:
import numpy as np 

# X = np.random.randint(0, 99, size=(10, 5))
# X_train = np.random.randint(0, 99, size=(9, 5))

num_test = X.shape[0]
num_train = X_train.shape[0]
dists = np.zeros((num_test, num_train))
for i in range(num_test):
    
    # First 
    # for j in range(num_train):
    #    dists[i, j] = np.sqrt( np.sum( (X[i]- X_train[j]) ** 2 ) )
    
    # Second 
    dists[i, :] = np.sqrt(np.sum((X[i] - X_train)**2, axis=1))
    
    # 3
    # dist = np.dot(X - X_train, (X - X_train).T)
    
dists    

array([[ 72.71175971,  58.06031347, 100.4788535 , 101.24228366,
         82.54695633,  41.07310556,  98.47334665,  71.85401868,
         56.86826883],
       [ 52.06726419, 149.70971912,  91.1592014 , 107.55463728,
         65.37583651,  88.0170438 ,  77.96794213,  88.79752249,
         70.41306697],
       [ 62.15303693,  93.33273809,  89.59910714,  87.14355972,
         70.32780389,  84.65813605,  58.38664231,  66.02272336,
         73.22567856],
       [ 85.24083528,  73.14369419, 104.95237015,  95.45155839,
        107.56858277, 100.88607436,  92.66067127,  56.86826883,
         89.80534505],
       [ 83.74365648,  96.27564593, 135.91173606, 134.46932736,
         90.21086409,  73.02739212, 107.96758773,  83.34866526,
         65.4369926 ],
       [ 67.06713055,  54.91812087,  76.70071708,  78.53024895,
         73.92563831,  47.138095  ,  81.17881497,  71.81921748,
         63.61603571],
       [136.17268449,  41.48493703, 128.96511156, 121.15279609,
        133.75350463,  97.7292